### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by ygrange**
Just proposing some minor changes after working through a good part of the notebook.,

### CODE REVIEW

**Comment by tammojan** [comment]
Hm, how do I merge one of the commits? 

I think in the exercise, it should really be UTC. Let's discuss over lunch.

**Comment by ygrange** [comment]
I also would like to suggest to add some answers (for example I would propose rewording the question "Execise: Does this measurement set contain any weights that are bigger than 1.0? (Use the function any().)"to "Execise: Show that this measurement set does not contain any weights that are bigger than 1.0? (Use the function any().)" (if it contains them, I did it wrong and haven't found out)

**Comment by ygrange** [comment]
(I can always change the pull request to add or remove commits. Let's discuss over lunch first)

**Comment by ygrange** [comment]
@tammojan Can you check again if you find the current version acceptabe to merge? I did some change of hisory...

And shall I just open a new one for the comment I just made?

**Comment by tammojan** [comment]
Thanks!

**Pull request merged**
